# Generated by Django 3.2.9 on 2021-11-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gen', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=100)),
                ('is_demo', models.BooleanField()),
            ],
        ),
    ]
