# Generated by Django 3.2.9 on 2021-11-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
