# Generated by Django 3.2.9 on 2021-11-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contact_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
