# Generated by Django 3.2.9 on 2021-12-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_register_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=100),
        ),
        migrations.AddField(
            model_name='register_table',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='prifile/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='register_table',
            name='update_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
